[package]
name = "microsoft_lepton_jpeg_rust_php"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ext-php-rs = "*"
lepton_jpeg = "*"

[profile.release]
strip = "debuginfo"
